CREATE TABLE CHEF (
    ID SERIAL NOT NULL,
    NAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE COOKBOOK (
    ID SERIAL NOT NULL ,
	NAME VARCHAR(30) NOT NULL,
	CHEF_ID INT REFERENCES CHEF(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE RECIPE (
	ID SERIAL NOT NULL,
	TITLE VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(100),
	CALORIES INTEGER,
	COOKBOOK_ID INT REFERENCES COOKBOOK(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE INGREDIENT (
	ID SERIAL NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	AMOUNT VARCHAR(30),
	RECIPE_ID INT REFERENCES RECIPE(ID),
	PRIMARY KEY (ID)
);

INSERT INTO CHEF (NAME, EMAIL, PASSWORD) VALUES ('The Chef', 'lisannewoudt@hotmail.com', '1');
INSERT INTO COOKBOOK (NAME, CHEF_ID) VALUES ('My first cookbook', 1);
INSERT INTO RECIPE (TITLE, DESCRIPTION, CALORIES, COOKBOOK_ID) VALUES ('My First Recipe', 'You should try this', 565, 1);
INSERT INTO INGREDIENT (NAME, AMOUNT, RECIPE_ID) VALUES ('Rice', '100 grams', 1);
INSERT INTO INGREDIENT (NAME, AMOUNT, RECIPE_ID) VALUES ('Paprika', '1 piece', 1);